//
//  DrawIntroPage.swift
//  ProjectName
//
//  Created by Nguyễn Phúc on 5/8/21.
//  Copyright © 2021 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class DrawIntroPage : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 416, height: 898), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 416, height: 898), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 416, y: resizedFrame.height / 898)


        //// Color Declarations
        let eb6e57 = UIColor(red: 0.180, green: 0.523, blue: 0.996, alpha: 1.000)

        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 0.5, y: 319.5))
        bezierPath.addLine(to: CGPoint(x: 418.5, y: 199.5))
        bezierPath.addLine(to: CGPoint(x: 418.5, y: 319.5))
        bezierPath.addLine(to: CGPoint(x: 0.5, y: 433.5))
        bezierPath.addLine(to: CGPoint(x: 0.5, y: 319.5))
        bezierPath.close()
        eb6e57.setFill()
        bezierPath.fill()
        UIColor.black.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 1.5, y: 432.5))
        bezier3Path.addLine(to: CGPoint(x: 418.5, y: 319.5))
        bezier3Path.addLine(to: CGPoint(x: 418.5, y: 432.5))
        bezier3Path.addLine(to: CGPoint(x: 1.5, y: 548.5))
        bezier3Path.addLine(to: CGPoint(x: 1.5, y: 432.5))
        bezier3Path.close()
        eb6e57.setFill()
        bezier3Path.fill()
        UIColor.black.setStroke()
        bezier3Path.lineWidth = 1
        bezier3Path.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 1.5, y: 546.5))
        bezier2Path.addLine(to: CGPoint(x: 418.5, y: 433.5))
        bezier2Path.addLine(to: CGPoint(x: 418.5, y: 546.5))
        bezier2Path.addLine(to: CGPoint(x: 1.5, y: 662.5))
        bezier2Path.addLine(to: CGPoint(x: 1.5, y: 546.5))
        bezier2Path.close()
        eb6e57.setFill()
        bezier2Path.fill()
        UIColor.black.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Oval Drawing
        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 269.5, y: 662.5, width: 102, height: 102))
        eb6e57.setFill()
        ovalPath.fill()
        UIColor.black.setStroke()
        ovalPath.lineWidth = 1
        ovalPath.stroke()
        
        context.restoreGState()

    }




    @objc(DrawIntroPageResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
